### ISSUE TITLE
pd_dic.py is currently broken 

### ISSUE THREAD

**Issue by ilyasst** [lm2-poly/PeriPyDIC#46]

**Comment by diehlpk** [comment]
Can you provide more details, since it is working for me

**Comment by ilyasst** [comment]
This is what I got:

```
(.env) buster@buster-VM:~/Repositories/PeriPyDIC$ python pd_dic.py -i examples/dic/input_DIC_2d.yaml -t dic
Traceback (most recent call last):
  File "pd_dic.py", line 109, in <module>
    main(sys.argv[1:])
  File "pd_dic.py", line 51, in main
    deck = IO.deck.DIC_deck(inputFile)
  File "/home/buster/Repositories/PeriPyDIC/peripydic/IO/deck.py", line 299, in __init__
    self.safety_factor = float(self.doc["Discretization"]["Safety_Factor"])
KeyError: 'Safety_Factor'
```

**Comment by ilyasst** [comment]
I tried it from #48 in a fresh environment:

```
(.env) buster@buster-VM:~/Repositories/PeriPyDIC/examples/dic$ python ../../pd_dic.py -i input_DIC_2d.yaml -t dic
Traceback (most recent call last):
  File "../../pd_dic.py", line 109, in <module>
    main(sys.argv[1:])
  File "../../pd_dic.py", line 51, in main
    deck = IO.deck.DIC_deck(inputFile)
  File "/home/buster/Repositories/PeriPyDIC/peripydic/IO/deck.py", line 299, in __init__
    self.safety_factor = float(self.doc["Discretization"]["Safety_Factor"])
KeyError: 'Safety_Factor'
```

**Comment by diehlpk** [comment]
Good catch, This was a bug in the deck and is fixed.
